apiVersion: v1 # Kubernetes API version
  kind: Service # Kubernetes resource kind we are creating
  metadata: # Metadata of the resource kind we are creating
    naame: spring-jenkins
  spec:
    selector:
      app: spring-jenkins
    ports:
      - protocol: "TCP"
        port: 8284 # The port that the service is running on in the cluster
        targetPort: 8284 # The port exposed by the service
    type: NodePort # type of the service.